
name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checkout Repo 
      - uses: actions/checkout@v4
      
      # Setup node
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      # Install node deps
      - name: Install dependencies
        run: npm ci

      # Run formatting
      - name: Linting
        run: npm run lint

      # Build node
      - name: Build
        run: npm run build

      # Pack
      - name: Pack
        run: npm run pack
      
      # Release Artifact
      - name: Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Github-Grain-Highlight
          path: extension.zip

      # TODO: Release to chrome web store